FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/inscritos/cmd/main
RUN go build -o /app/inscritos/inscritos .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/inscritos/inscritos .

EXPOSE 8083
CMD ["./inscritos"]