FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/prospectos/cmd/main
RUN go build -o /app/prospectos/prospectos .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/prospectos/prospectos .

EXPOSE 8082
CMD ["./prospectos"]